### ISSUE TITLE
Activity/Fragment

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [CSC-MobDev-2016/lessson8#1]
Кто за что должен отвечать, если у меня активити, а на ней куча фрагментов?

Когда была только активити, в ней же был CursorLoader, загрузка из таблицы, все остальное. Теперь на активити 2 фрагмента, один со списком, второй с подробной информацией. Фрагменты еще и не знают про application context. Что оставить на активити, а что можно запихать во фрагменты? Могут ли они вообще видеть, что происходит в активити?

**Comment by thevery** [comment]
Фрагмент сам загружает данные и, соответственно, `implements LoaderManager.LoaderCallbacks<Cursor>`, метод `getLoaderManager().initLoader` вызывается в `onCreateView` итд (см. например, тут: http://developer.android.com/guide/components/loaders.html#example). Активити при этом реализует коллбэки типа `onCitySelected` и меняет один фрагмент на другой через `FragmentManager` либо  вызывает какие-то методы у фрагмента напрямую.

**Comment by AnastasiaSulyagina** [comment]
Спасибо

**Comment by thevery** [comment]
http://developer.android.com/intl/ru/training/basics/fragments/communicating.html
